name: Release Python Package

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    needs: [unit]
    environment: release
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip
        cache-dependency-path: '**/pyproject.toml'
    - name: Install dependencies
      run: |
        make install
        pip install setuptools wheel build
    - name: Build
      run: make build
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
